### ISSUE TITLE
VR unsupported (ZeroTier)

### ISSUE THREAD

**Issue by antonioarbues** [vuer-ai/vuer#20]
Hi,

I am using vuer to stream a stereo camera image pair to my vr headset. i am streaming on `0.0.0.0` port `8012`.
if i connect my meta quest 2 via usb-c and i run `adb reverse tcp:8012 tcp:8012`, everything works fine, as i am able to open the page at localhost:8012 and to click on "open VR" and start the vr experience.

Now, i want to remove the need to use tcp and a material usbc cable and instead i want to open the stream directly to the headset. so i added my headset to my ZeroTier network (a tool that establishes LAN connectivity between devices) and i opened the corresponding web page.
Here, instead of having "open VR", I have "VR unsupported".

Any idea on how to fix this?
Cheers!

**Comment by antonioarbues** [comment]
Solved: you need to be on HTTPS and I was on HTTP.

**Comment by Skvayzer** [comment]
Hello! How did you use Zerotier with Vuer?
I have a problem that I cannot access Vuer page via https.
I tried to do reverse proxy, local tunnel (alternative for ngrok), but I did not succeed because of many problems.
Moreover, the Vuer documentation for self-singed certificates leads to a broken webpage.

I wonder how you managed to do this.
